//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp37
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazine
    {
        public int IdOrder { get; set; }
        public int IdBook { get; set; }
        public int Quantity { get; set; }
        public string Provider { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Provider Provider1 { get; set; }
    }
}
