//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp37
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookShopEntities : DbContext
    {
        public BookShopEntities()
            : base("name=BookShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Gener> Gener { get; set; }
        public virtual DbSet<Magazine> Magazine { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<ShelingUnitHall> ShelingUnitHall { get; set; }
        public virtual DbSet<ShelingWarehouse> ShelingWarehouse { get; set; }
        public virtual DbSet<shulf> shulf { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<ThemeName> ThemeName { get; set; }
    }
}
